### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by la0wei** [wy580477/Alist-EX-container#2]
yml文件内修改了一个二级域名，端口设置443
主页打不开，F12查看， 发现502错误。
/qbitweb 同样502
/portalpage 可以显示
/qbitvue 可以显示

直接在宿主机ps -e 查看，能看到有qbittorrent、aria2等运行
附配置：
version: '3.3'
services:
  alist-ex:
    image: ghcr.io/wy580477/alist-ex-container:latest
    container_name: alist-ex
    network_mode: host
    restart: unless-stopped
    volumes:
      - /1st:/data
    environment:
      CADDY_DOMAIN: "一个二级域名"

      CADDY_EMAIL: 10000@qq.com

      CADDY_WEB_PORT: 443

      ARIA2_TOKEN: "这里修改了token"

      ARIA2_TRACKER_UPDATE: "enable"
     
      TZ: Asia/Shanghai
      ALIST_PORT: 61600
      ARIA2_PORT: 61601
      QBT_WEBUI_PORT: 61602

**Comment by wy580477** [comment]
贴一下容器的日志，以及 log 目录下 qbit 的日志。

**Comment by la0wei** [comment]
root@vps:docker logs alist-ex
INFO[2023-09-04 01:38:30] reading config file: data/config.json        
INFO[2023-09-04 01:38:30] load config from env with prefix:            
INFO[2023-09-04 01:38:30] init logrus...                               
INFO[2023-09-04 01:38:30] start HTTP server @ 127.0.0.1:61600          
INFO[2023-09-04 01:38:30] Aria2 not ready.                             
INFO[2023-09-04 01:38:30] qbittorrent not ready.  

root@vps:/storage/log/qBittorrent# ls
@4000000064f4c4a0067ba13c.u  current  lock
root@vps:/storage/log/qBittorrent# cat @4000000064f4c4a0067ba13c.u 
WebUI will be started shortly after internal preparations. Please wait...

**Comment by wy580477** [comment]
> INFO[2023-09-04 01:38:30] start HTTP server @ 127.0.0.1:61600

奇怪服务跑起来了啊。是怎么访问 502 报错的，是直接访问 CADDY_WEB_PORT 嘛？中间有经过别的反向代理嘛？

log 目录下 caddy 日志发一下。

**Comment by la0wei** [comment]
CADDY_WEB_PORT设置了443，浏览时直接输https域名就行，缺省就是443端口。只在docker里用了这个caddy，没有其他docker容器

root@vps:/storage/log/caddy# ls
@4000000064f4c4a006693a4c.u  current  lock
root@vps:/storage/log/caddy# cat @4000000064f4c4a006693a4c.u
current文件和@4000000064f4c4a006693a4c.u基本一致

{"level":"error","ts":1693762501.6693237,"logger":"http.log.error","msg":"dial tcp [::1]:61600: connect: connection refused","request":{"remote_ip":"此处IP打码","remote_port":"50340","proto":"HTTP/1.1","method":"GET","host":"网站二级域名","uri":"/","headers":{"Connection":["keep-alive"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"],"Accept-Encoding":["gzip, deflate"],"Accept":["*/*"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"http/1.1","server_name":"网站二级域名"}},"duration":0.000253536,"status":502,"err_id":"i3v67abcz","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}

{"level":"error","ts":1693762501.7812972,"logger":"http.log.error","msg":"dial tcp [::1]:61600: connect: connection refused","request":{"remote_ip":"此处IP打码","remote_port":"10563","proto":"HTTP/1.1","method":"GET","host":"网站二级域名","uri":"/","headers":{"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"],"Accept-Encoding":["gzip, deflate"],"Accept":["*/*"],"Connection":["keep-alive"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"http/1.1","server_name":"网站二级域名"}},"duration":0.000258106,"status":502,"err_id":"e3c2b4662","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}

**Comment by wy580477** [comment]
> {"level":"error","ts":1693762501.6693237,"logger":"http.log.error","msg":"dial tcp [::1]:61600: connect: connection refused","request":{"remote_ip":"此处IP打码","remote_port":"50340","proto":"HTTP/1.1","method":"GET","host":"网站二级域名","uri":"/","headers":{"Connection":["keep-alive"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"],"Accept-Encoding":["gzip, deflate"],"Accept":["_/_"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"http/1.1","server_name":"网站二级域名"}},"duration":0.000253536,"status":502,"err_id":"i3v67abcz","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
> 
> {"level":"error","ts":1693762501.7812972,"logger":"http.log.error","msg":"dial tcp [::1]:61600: connect: connection refused","request":{"remote_ip":"此处IP打码","remote_port":"10563","proto":"HTTP/1.1","method":"GET","host":"网站二级域名","uri":"/","headers":{"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"],"Accept-Encoding":["gzip, deflate"],"Accept":["_/_"],"Connection":["keep-alive"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"http/1.1","server_name":"网站二级域名"}},"duration":0.000258106,"status":502,"err_id":"e3c2b4662","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}

大概我知道啥原因了，caddy 反代到 localhost 时只尝试连接了 ::1 , 没有尝试连接 127.0.0.1。 

我这里不能复现。感觉是不是你那边系统 hosts 有问题。

/etc/hosts 文件里有 "127.0.0.1       localhost" 嘛

**Comment by la0wei** [comment]
厉害！果然是/etc/hosts没有127.0.0.1 localhost的问题
我都没注意到日志里tcp [::1]:61600 实际是ipv6。
修改后已可以访问了。谢谢！
